### ISSUE TITLE
Simplify CMake default config options

### ISSUE THREAD

**Issue by BishopGIS** [nextgis-borsch/lib_gdal#14]
Add CMake default option to build like such approach:

> git clone .../gdal
> mkdir build
> cd build
> cmake ..
> apps/gdalinfo --version

**Comment by BishopGIS** [comment]
> git clone --depth 1 https://github.com/nextgis-borsch/lib_gdal.git gdal
> cd gdal
> mkdir build
> cd build
> cmake ..
> cmake --build . --config release
> cmake --build . --config release --target package

Get archives from _CPack_Packages\win32 (ZIP and NSIS).
It's expected VS, Python and NSIS installed.
@mloskot can you test this?

**Comment by mloskot** [comment]
@BishopGIS Sorry it took me so long.

First, I'm testing on Ubuntu.

I understand the internal libraries (eg. json-c) are not available in the CMake'ified GDAL codebase. Fine.
So, I installed GDAL deps with `apt` packages.

`cmake` stopped at missing OpenCAD:
```
-- Not found OpenCAD in packages. Try look in system.
-- Could NOT find OPENCAD (missing:  OPENCAD_LIBRARY OPENCAD_INCLUDE_DIR)
CMake Error at cmake/FindAnyProject.cmake:186 (message):
  OpenCAD is required in gdal!
Call Stack (most recent call first):
  drivers/common/cad/CMakeLists.txt:51 (find_anyproject)
```

It is internal library in GDAL upstream repo.
Looks like you haven't packaged the library it for ;-)

Does OpenCAD have to be required?

**Comment by BishopGIS** [comment]
@mloskot  OpenCAD driver is not required. But it builds by default in GDAL (http://gdal.org/ogr_formats.html) and so this driver is ON by default. You can install libopencad-dev from our ppa (https://launchpad.net/~nextgis/+archive/ubuntu/ppa/+packages) or disable it via `-DENABLE_CAD=OFF`.

Do you think we need to disable this driver in default config options for Linux build? 
On Linux for default config we expected all dependencies are installed via package manager.

**Comment by mloskot** [comment]
If you ask me, if a driver belongs to optional set, then I'd make its dependency optional by default. Then, user only looks for required ppa or options if really needs to use that driver.

For one or two,  it's not a problem to `-DENABLE_CAD=OFF`, but there might be plenty such drivers, I assume. Then it multiple iterations of cmake, find dependency or disable with `OFF`, run cmake, ... become a hassle.

Again, my 2 cents
