### ISSUE TITLE
HDF can't be opened

### ISSUE THREAD

**Issue by simgislab** [nextgis-borsch/lib_gdal#19]
>c:\temp>gdalinfo MOD09A1.A2016241.h20v01.005.2016250103354.hdf
ERROR 4: `MOD09A1.A2016241.h20v01.005.2016250103354.hdf' not recognized as a sup
ported file format.
gdalinfo failed - unable to open 'MOD09A1.A2016241.h20v01.005.2016250103354.hdf'

**Comment by BishopGIS** [comment]
This is not GDAL problem. NextGIS Installer (https://github.com/nextgis/nextgis_installer/issues) build without  https://github.com/nextgis-borsch/lib_hdf4 and HDF driver. The available drivers are listed here: https://github.com/nextgis-borsch/lib_gdal/blob/master/README.md
