### ISSUE TITLE
Where is tools.py?

### ISSUE THREAD

**Issue by ghost** [nextgis-borsch/lib_gdal#25]
`tools.py` is supposed to be in `opt/` according to README.txt - do you have a copy of it?

**Comment by BishopGIS** [comment]
The note in readme `Go to borsch repository (opt folder) and execute` means go to [borsch repository](https://github.com/nextgis-borsch/borsch). The `tools.py` is here: https://github.com/nextgis-borsch/borsch/tree/master/opt

**Comment by ghost** [comment]
Oops, missed the note about the different report. Thanks!
