### ISSUE TITLE
CMake fails

### ISSUE THREAD

**Issue by kerim371** [nextgis-borsch/lib_gdal#30]
Hi,

When leaving default value WITH_JPEG12 = TRUE then we I error:

**CMake Error at cmake/FindExtProject.cmake:562 (add_dependencies):
  add_dependencies called with incorrect number of arguments
Call Stack (most recent call first):
  cmake/FindAnyProject.cmake:77 (find_extproject)
  drivers/raster/CMakeLists.txt:58 (find_anyproject)**

Setting WITH_JPEG12 = FALSE solves the problem.

But the main problem is when I try to build with PROJ support I get errors:

CMake Error at C:/apps/_BUILD/GDAL_3.1.2/third-party/build/PROJ_EP-build/PROJConfig.cmake:9 (include):
  include could not find load file:

    C:/apps/_BUILD/GDAL_3.1.2/third-party/build/PROJ_EP-build/PROJTargets.cmake
Call Stack (most recent call first):
  cmake/FindExtProject.cmake:539 (include)
  cmake/FindAnyProject.cmake:77 (find_extproject)
  CMakeLists.txt:195 (find_anyproject)

CMake Error at C:/apps/_BUILD/GDAL_3.1.2/third-party/build/PROJ_EP-build/PROJConfig.cmake:11 (get_property):
  get_property could not find TARGET proj.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  cmake/FindExtProject.cmake:539 (include)
  cmake/FindAnyProject.cmake:77 (find_extproject)
  CMakeLists.txt:195 (find_anyproject)

CMake Error at cmake/FindExtProject.cmake:556 (set_target_properties):
  set_target_properties Can not find target to add properties to: proj
Call Stack (most recent call first):
  cmake/FindAnyProject.cmake:77 (find_extproject)
  CMakeLists.txt:195 (find_anyproject)

This happens not only with PROJ library but with some other. Is it fine?

**Comment by BishopGIS** [comment]
Looks like a bug.
@514ckw4r3 try following steps https://github.com/nextgis-borsch/lib_gdal/issues/14#issuecomment-301016193 (except packaging) to reproduce. Expected behaviour - everything build fine.

**Comment by kerim371** [comment]
@BishopGIS thank you for response. 
Ok I will now try follow the link you gave (give me one hour) but I think this was my fault. 

Details:
When I launch CMake gui to build GDAL  I can see that most options that starts with `WITH_` keyword are ckecked by default. For example `WITH_TIFF` and `WITH_TIFF_EXTERNAL` are checked ON. If I leave only `WITH_ANY_LIB_EXTERNAL` as ON and disable `WITH_ANY_OTHER_LIB` then I can configure without problems but I havent tested to compile it yet. I will give the report when I get some results.

**Comment by kerim371** [comment]
@BishopGIS I've tried to follow commands you gave in the link above:
```bash
git clone --depth 1 https://github.com/nextgis-borsch/lib_gdal.git gdal
cd gdal
mkdir build
cd build
cmake ..  # here I get errors
```
I attach the cmake output. I think is beacause of default gdal settings.

Today I will try to build lib_gdal with only external libraries checked.

[lib_gdal_CMake_output.txt](https://github.com/nextgis-borsch/lib_gdal/files/6102931/lib_gdal_CMake_output.txt)

**Comment by kerim371** [comment]
@BishopGIS I've just tried to leave only `WITH_ANY_EXTERNAL` checked ON and the configuration passes fine.
But while building it I get many errors I show them on the picture. And the cmake cache I attach to the post.
[CMakeCache.txt](https://github.com/nextgis-borsch/lib_gdal/files/6104966/CMakeCache.txt)

![image](https://user-images.githubusercontent.com/43808863/110400278-6b5b8680-8088-11eb-9708-3081e997741d.png)

**Comment by 514ckw4r3** [comment]
Hi @kerim371,

Build scripts updated.
I have successfully built the project on msvc++ v14.16 using the following commands:

> ```cmake .. -DWITH_ZLIB=ON -DWITH_ZLIB_EXTERNAL=ON -DWITH_EXPAT=ON -DWITH_EXPAT_EXTERNAL=ON -DWITH_JSONC=ON -DWITH_JSONC_EXTERNAL=ON -DWITH_ICONV=ON -DWITH_CURL=ON -DWITH_CURL_EXTERNAL=ON -DWITH_LibXml2=ON -DWITH_LibXml2_EXTERNAL=ON -DWITH_GEOS=ON -DWITH_GEOS_EXTERNAL=ON -DWITH_JPEG=ON -DWITH_JPEG_EXTERNAL=ON -DWITH_JPEG12=ON -DWITH_JPEG12_EXTERNAL=ON -DWITH_TIFF=ON -DWITH_TIFF_EXTERNAL=ON -DWITH_GeoTIFF=ON -DWITH_GeoTIFF_EXTERNAL=ON -DWITH_JBIG=ON -DWITH_JBIG_EXTERNAL=ON -DWITH_GIF=ON -DWITH_GIF_EXTERNAL=ON -DWITH_OpenCAD=ON -DWITH_OpenCAD_EXTERNAL=ON -DWITH_PNG=ON -DWITH_PNG_EXTERNAL=ON -DWITH_PROJ=ON -DWITH_PROJ_EXTERNAL=ON -DWITH_OpenJPEG=ON -DWITH_OpenJPEG_EXTERNAL=ON -DENABLE_OPENJPEG=ON -DWITH_OpenSSL=ON -DWITH_OpenSSL_EXTERNAL=ON -DWITH_LibLZMA=ON -DWITH_LibLZMA_EXTERNAL=ON -DWITH_PYTHON=ON -DWITH_PYTHON3=ON -DENABLE_OZI=ON -DENABLE_NITF_RPFTOC_ECRGTOC=ON -DGDAL_ENABLE_GNM=ON -DWITH_OCI=ON -DWITH_OCI_EXTERNAL=ON -DENABLE_OCI=ON -DENABLE_GEORASTER=ON -DWITH_SQLite3=ON -DWITH_SQLite3_EXTERNAL=ON -DWITH_PostgreSQL=ON -DWITH_PostgreSQL_EXTERNAL=ON -WITH_Boost=ON -DWITH_Boost_EXTERNAL=ON -DWITH_KML=ON -DWITH_KML_EXTERNAL=ON -DGDAL_BUILD_APPS=ON -DWITH_HDF4=ON -DWITH_HDF4_EXTERNAL=ON -DENABLE_HDF4=ON -DWITH_QHULL=ON -DWITH_QHULL_EXTERNAL=ON -DWITH_Spatialite=ON -DWITH_Spatialite_EXTERNAL=ON -DWITH_SZIP=ON -DWITH_SZIP_EXTERNAL=ON -DWITH_UriParser=ON -DWITH_UriParser_EXTERNAL=ON -DWITH_NUMPY=ON -DENABLE_WEBP=ON -DWITH_WEBP=ON -DWITH_WEBP_EXTERNAL=ON -DBUILD_TESTING=ON -DSKIP_PYTHON_TESTS=ON -DWITH_GTest=ON -DWITH_GTest_EXTERNAL=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release```

>```cmake --build . --config Release --target package```

**Comment by kerim371** [comment]
@BishopGIS I just tested with the configuration you provided on Windows 10 and cmake configuration fails. 
```bash
# skip many lines of successful output
-- SPATIALITE VERSION IS GREATER 4.1.1
-- add raster format: ←[34maaigrid←[m
-- add raster format: ←[34madrg←[m
# skip many lines of successful output
-- add vector format: ←[34mxplane←[m
-- add raster+vector format: ←[34mcad←[m
-- ←[31mSkip cad←[m
-- add raster+vector format: ←[34mgpkg←[m
-- add raster+vector format: ←[34mngw←[m
-- add raster+vector format: ←[34mnull←[m
-- add raster+vector format: ←[34mplscenes←[m
-- add gnm format: ←[34mfile←[m
-- Found PythonInterp: E:/python-3.9.4-embed-amd64/python.exe (found suitable version "3.9.4", minimum required is "2") 
-- Found PythonInterp: E:/python-3.9.4-embed-amd64/python.exe (found suitable version "3.9.4", minimum required is "3") 
-- Not found NUMPY in packages. Try look in system.
CMake Warning at cmake/FindAnyProject.cmake:116 (find_package):
  By not providing "FindNUMPY.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NUMPY", but
  CMake did not find one.

  Could not find a package configuration file provided by "NUMPY" with any of
  the following names:

    NUMPYConfig.cmake
    numpy-config.cmake

  Add the installation prefix of "NUMPY" to CMAKE_PREFIX_PATH or set
  "NUMPY_DIR" to a directory containing one of the above files.  If "NUMPY"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  bindings/python/CMakeLists.txt:97 (find_anyproject)


CMake Warning at cmake/FindAnyProject.cmake:192 (message):
  NUMPY not found and will be disabled in gdal!
Call Stack (most recent call first):
  bindings/python/CMakeLists.txt:97 (find_anyproject)


CMake Error at cmake/FindExtProject.cmake:558 (add_dependencies):
  add_dependencies called with incorrect number of arguments
Call Stack (most recent call first):
  cmake/FindAnyProject.cmake:77 (find_extproject)
  tests/cpp/CMakeLists.txt:36 (find_anyproject)


CMake Error at cmake/FindAnyProject.cmake:190 (message):
  OpenSSL is required in gdal!
Call Stack (most recent call first):
  tests/cpp/CMakeLists.txt:36 (find_anyproject)


-- Configuring incomplete, errors occurred!
See also "E:/tmp/lib_gdal/build/CMakeFiles/CMakeOutput.log".
See also "E:/tmp/lib_gdal/build/CMakeFiles/CMakeError.log".

E:\tmp\lib_gdal\build>
```

Also I get error when configuring lib_gdal on almost fresh Ubuntu 20.04. Here I can normally compile lib_gdal only after `sudo apt-get install libgdal-dev python3-gdal gdal-bin`. Of course in this case I lose the benefit of cmake external build :)
By the way I also follow the steps from [#14 ](https://github.com/nextgis-borsch/lib_gdal/issues/14)

I would appreciate if there were an opportynity to crossplatform build lib_gdal and default cmake options were customized in assumption that OS is fresh (maybe python is preinstalled). At least on Linux default cmake configuration should be aimed at fresh OS I think.

P.S. the most annoying error is:
```bash
CMake Error at cmake/FindExtProject.cmake:561 (add_dependencies):
  add_dependencies called with incorrect number of arguments
Call Stack (most recent call first):
  cmake/FindAnyProject.cmake:79 (find_extproject)
  CMakeLists.txt:195 (find_anyproject)
```
Error happens when cmake tries to get data from empty variable. Maybe it is cmake version issue? I use cmake 3.19.2

**Comment by BishopGIS** [comment]
@kerim371 Hi,
1. Windows builds tested without python packages. This is your responsibility to install python dependencies via pip. Only C/C++ builds now supported. 
2. Ubuntu is not supported by borsch. This is your responsibility to install needed dependencies. You can see debian files for complete dependencies list here: https://github.com/nextgis/ppa/blob/master/gdal/debian/control 

So all behavior is expected.
