### ISSUE TITLE
В слое границ Приморья из NGW в GeoJSON видна только одна фича из множества

### ISSUE THREAD

**Issue by trolleway** [nextgis-borsch/lib_gdal#6]
Файл: http://opendata25.primorsky.ru/ngw/api/resource/176/geojson (публичный)
Все объекты: 
![2016-05-31 18-20-06](https://cloud.githubusercontent.com/assets/4630662/15679924/642e519c-275c-11e6-8a6a-f5662ed1de5d.png)

Вид в QGIS и NextGIS Manager с БОРЩGDAL:
![image](https://cloud.githubusercontent.com/assets/4630662/15679966/7f1b97ee-275c-11e6-9ced-3cdc1530b1da.png)

**Comment by trolleway** [comment]
Файл в архиве: [primorie_boundaries.zip](https://github.com/nextgis-borsch/lib_gdal/files/291481/primorie_boundaries.zip)

**Comment by BishopGIS** [comment]
Проблема:
а) в том что ты загрузил данные с запрещенным полем ID
б) в GDAL 2 добавили редактирование и поэтому понадобились идентификаторы фич, а у тебя в поле ID все 0, поэтому фичи перекрывали друг друга. Завел тикет в GDAL https://trac.osgeo.org/gdal/ticket/6538
