### ISSUE TITLE
gnmmanage: Падает при выполнении autoconnect

### ISSUE THREAD

**Issue by drnextgis** [nextgis-borsch/lib_gdal#9]
```
$ gnmmanage create -f "GNMFile" -t_srs "EPSG:4326" ~/tmp/gnmnetwork
$ gnmmanage import ~/download/RU-ALT/data -l railway-line ~/tmp/gnmnetwork
$ gnmmanage import ~/download/RU-ALT/data -l railway-station-point ~/tmp/gnmnetwork
$ gnmmanage autoconnect 0.00005 ~/tmp/gnmnetwork
No layers provided. Use all layers of network:
1. railway-line
2. railway-station-point
Segmentation fault (core dumped)
```

Исходные данные: [dataset.zip](https://github.com/nextgis-borsch/lib_gdal/files/446711/dataset.zip)

**Comment by BishopGIS** [comment]
Connected ticket https://trac.osgeo.org/gdal/ticket/6876

![2017-07-11 17 41 57](https://user-images.githubusercontent.com/1708122/28074186-9c5af3ec-6660-11e7-9388-57d07c5a59a3.png)

**Comment by BishopGIS** [comment]
The problem was with linestring and multilinestring mixing in shapefile.

**Comment by BishopGIS** [comment]
Fix in r39547
